app:
    name: Template Spring MVC Empty Project
    description: ${app.name} is a Spring Boot app
    version: 0.1-SNAPSHOT

spring.main.show-banner: false

logging:
    level:
        org:
            springframework: INFO
            springframework.test: INFO
